const dotenv = require('dotenv')


dotenv.config()

module.exports = { 
    PORT  : process.env.PORT,
  
    INTERNAL_SERVER_TOKEN: process.env.INTERNAL_SERVER_TOKEN,
    MANGODB_URL: process.env.MANGODB_URL,
    PRIVATEJWT: process.env.PRIVATEJWT,
    BATTELE_GAME_DB_URL: process.env.BATTELE_GAME_DB_URL,

    MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
    CHANNEL_NAME: process.env.CHANNEL_NAME,
    EXCHANGE_NAME: process.env.EXCHANGE_NAME,
    REMINDER_BINDING_KEY: process.env.REMINDER_BINDING_KEY,
    
    MATCH_BACKEND_URL: process.env.MATCH_BACKEND_URL,
    PLAYER_GAME_BACKEND_URL: process.env.PLAYER_GAME_BACKEND_URL,
    CONTEST_BACKEND_URL: process.env.CONTEST_BACKEND_URL,
    LEADERBOARD_BACKEND_URL: process.env.LEADERBOARD_BACKEND_URL,
    PAYMENT_BACKEND_URL: process.env.PAYMENT_BACKEND_URL,
    AUTH_BACKEND_URL: process.env.AUTH_BACKEND_URL,


}